name: Deploy FE to Shared Hosting

on:
  push:
    branches: [ main, master ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install NPM dependencies and build
      run: |
        npm ci
        npm run build

    - name: Create deployment artifacts (Webpack)
      run: |
        mkdir deployment
        cp -R dist/* deployment/
        
        # Copy only frontend build files
        if [ -d "dist" ]; then
          cp -R dist/* deployment/
        elif [ -d "build" ]; then
          cp -R build/* deployment/
        elif [ -d "public" ]; then
          cp -R public/* deployment/
        else
          # Copy common frontend files
          cp -R *.html deployment/ 2>/dev/null || true
          cp -R *.css deployment/ 2>/dev/null || true
          cp -R *.js deployment/ 2>/dev/null || true
          cp -R assets deployment/ 2>/dev/null || true
          cp -R images deployment/ 2>/dev/null || true
          cp -R css deployment/ 2>/dev/null || true
          cp -R js deployment/ 2>/dev/null || true
        fi
        
        # Create .htaccess for clean URLs (if using Apache)
        cat > deployment/.htaccess << 'EOF'
        <IfModule mod_rewrite.c>
          RewriteEngine On
          
          # Handle client-side routing for SPAs
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          
          # Enable compression
          <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
            AddOutputFilterByType DEFLATE application/javascript text/javascript
          </IfModule>
          
          # Set caching headers
          <IfModule mod_expires.c>
            ExpiresActive on
            ExpiresByType text/css "access plus 1 month"
            ExpiresByType application/javascript "access plus 1 month"
            ExpiresByType image/png "access plus 1 month"
            ExpiresByType image/jpeg "access plus 1 month"
          </IfModule>
        </IfModule>
        EOF

    - name: Deploy to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/
        server-dir: ${{ secrets.FTP_TARGET }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.md
          .github/
          .gitignore
        log-level: verbose