name: Deploy FE to Shared Hosting

on:
  push:
    branches: [ main, master ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        echo "Build output directory contents:"
        ls -la dist/ 2>/dev/null || ls -la build/ 2>/dev/null || echo "No dist/ or build/ directory found"
        echo ""
        echo "Root directory contents:"
        ls -la

    - name: Create deployment artifacts
      run: |
        mkdir -p deployment
        
        # Webpack typically outputs to dist/ directory
        if [ -d "dist" ]; then
          echo "Copying dist/ directory"
          cp -R dist/* deployment/
        elif [ -d "build" ]; then
          echo "Copying build/ directory"
          cp -R build/* deployment/
        else
          echo "ERROR: No build output directory found!"
          exit 1
        fi
        
        # Copy .htaccess if it exists
        if [ -f ".htaccess" ]; then
          cp .htaccess deployment/
        else
          # Create .htaccess for SPA routing
          cat > deployment/.htaccess << 'EOF'
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  
  # Handle SPA routing - redirect all requests to index.html
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>

# Enable GZIP compression
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html
  AddOutputFilterByType DEFLATE text/css
  AddOutputFilterByType DEFLATE text/javascript
  AddOutputFilterByType DEFLATE application/javascript
  AddOutputFilterByType DEFLATE application/json
</IfModule>

# Browser caching
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/jpg "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/gif "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType font/woff "access plus 1 year"
  ExpiresByType font/woff2 "access plus 1 year"
  ExpiresByType text/html "access plus 0 seconds"
</IfModule>

# Security headers
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set X-XSS-Protection "1; mode=block"
</IfModule>
EOF
        fi
        
        echo ""
        echo "Deployment directory contents:"
        ls -la deployment/

    - name: Deploy to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deployment/
        server-dir: ${{ secrets.FTP_TARGET }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.md
          .github/
          .gitignore
          src/
          webpack.config.js
          postcss.config.js
          tailwind.config.js
          package*.json
          babel.config.js
          .babelrc
        log-level: verbose